services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    attach: false
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    # Only enable this if you have a GPU and the NVIDIA runtime installed
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    restart: unless-stopped

volumes:
  ollama: